### ISSUE TITLE
NPE on teleportation from other world

### ISSUE THREAD

**Issue by cjm721** [Bartz24/VoidIslandControl#17]
```
[23:03:07] [Server thread/WARN]: Couldn't process command: island home
java.lang.NullPointerException: null
        at net.minecraft.world.Teleporter.func_180620_b(SourceFile:128) ~[anc.class:?]
        at net.minecraft.world.Teleporter.func_180266_a(SourceFile:65) ~[anc.class:?]
        at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:707) ~[pl.class:?]
        at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:617) ~[pl.class:?]
        at net.minecraft.server.management.PlayerList.func_187242_a(PlayerList.java:604) ~[pl.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_184204_a(EntityPlayerMP.java:695) ~[oq.class:?]
        at com.bartz24.voidislandcontrol.PlatformCommand.tpHome(PlatformCommand.java:553) ~[PlatformCommand.class:?]
        at com.bartz24.voidislandcontrol.PlatformCommand.func_184881_a(PlatformCommand.java:129) ~[PlatformCommand.class:?]
        at com.feed_the_beast.ftbu.ranks.CmdOverride.func_184881_a(CmdOverride.java:70) ~[CmdOverride.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:950) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:929) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by Bartz24** [comment]
Probably been too long for me to know where the issue occurred.

If the NPE happens again, it would be nice to have an up to date log!
