### ISSUE TITLE
Broken dimension support

### ISSUE THREAD

**Issue by RealLith** [Bartz24/VoidIslandControl#39]
Even tho this mod has an option to pick witch dimension you wish to have an island on, it aint working. I tried with multiple dimensions: -11325 (extrautils2 deep dark), -2 (advanced rocketry space station) and even -1 VANILLA minecraft nether dimension. What happends is on world creation you spawn in a world in the void and die (no  platform) and when executing a command "/island create" you get send to that dimension (the one I picked in the config folder) But you are unable to move, unable to place or break blocks. basicly you are frozen only can spin around 360 and type in chat. The world is void - no island no nothing. After you relog into the world then you can move and place blocks but the island still does not generate. what generates is a nether portal (dosent matter what dimension, its still a nether portal). And this happends constantly. 

Version of the game: 1.12.2
forge and mod is latest (I litteraly downloaded it like 15mins ago using the Twitch launcher).
singleplayer

here is a error that I get in the logs file when executing the "/island create" command:

[23:12:48] [Server thread/INFO] [FML]: Loading dimension -2 (New World) (net.minecraft.server.integrated.IntegratedServer@683b7aee)
[23:12:48] [main/INFO] [journeymap]: Mapping halted in D:\Curse Modpacks\Instances\Meteorite\journeymap\data\sp\New World~\DIM0
[23:12:52] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[23:12:52] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
[23:12:52] [main/INFO] [journeymap]: Loading journeymap.topo.config
[23:12:52] [main/INFO] [journeymap]: Loaded 1 waypoints from D:\Curse Modpacks\Instances\Meteorite\journeymap\data\sp\New World~\waypoints
[23:12:52] [main/INFO] [journeymap]: Mapping started in D:\Curse Modpacks\Instances\Meteorite\journeymap\data\sp\New World~\DIM-2. Memory: 3446MB total, 2222MB free 
[23:12:59] [Server thread/WARN] [net.minecraft.command.CommandHandler]: Couldn't process command: island create test
java.lang.NullPointerException: null
	at net.minecraft.world.Teleporter.func_180620_b(Teleporter.java:134) ~[anc.class:?]
	at net.minecraft.world.Teleporter.func_180266_a(Teleporter.java:37) ~[anc.class:?]
	at net.minecraft.world.Teleporter.placeEntity(Teleporter.java:436) ~[anc.class:?]
	at net.minecraft.server.management.PlayerList.transferEntityToWorld(PlayerList.java:720) ~[pl.class:?]
	at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:623) ~[pl.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.changeDimension(EntityPlayerMP.java:695) ~[oq.class:?]
	at net.minecraft.entity.Entity.func_184204_a(Entity.java:2540) ~[vg.class:?]
	at com.bartz24.voidislandcontrol.PlatformCommand.newPlatform(PlatformCommand.java:386) ~[PlatformCommand.class:?]
	at com.bartz24.voidislandcontrol.PlatformCommand.func_184881_a(PlatformCommand.java:115) ~[PlatformCommand.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[23:12:59] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] An unknown error occurred while attempting to perform this command
[23:12:59] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 10959ms behind, skipping 219 tick(s)
[23:12:59] [Server thread/INFO] [journeymap]: Mapping halted in D:\Curse Modpacks\Instances\Meteorite\journeymap\data\sp\New World~\DIM-2
[23:12:59] [Server thread/INFO] [FML]: Unloading dimension -2
[23:12:59] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): optionsManagerViewed=null
[23:12:59] [main/WARN] [journeymap]: core (Initialized) Bad configField entry during updateFrom(): splashViewed=null
[23:12:59] [main/INFO] [journeymap]: Loading journeymap.topo.config

p.s. the "/island create test" test is a island type that i tried to make as a test to see if it would work. The 'test" island generates in the 0 dimension (overworld) but not in other dimensions (none of the island types work in other dimensions).

For biome:

When ever you set a biome that Is not from vanilla minecraft it will automaticly generate plains biome. I found that In order to bypass that you HAVE to install biome tweaker to be able to make biomes other then vanilla.

**Comment by Bartz24** [comment]
I fixed the dimension issues

I'll move the biome stuff to a new issue
