### ISSUE TITLE
NPE attempting to use visit

### ISSUE THREAD

**Issue by marcmagus** [Bartz24/VoidIslandControl#54]
In a new GregBlock (https://minecraft.curseforge.com/projects/gregblock) server, attempted to test out the /island visit command to visit an offline player.

I get the error "An unknown error occurred while attempting to perform this command"

Testing a bit, I get the same error if I use a fake name like "/island visit nobody". If I use my own name I get the expected "Can't visit your own island."

It's slightly unclear if I'm supposed to be able to visit an offline player (I had thought so), but at the very least this should give a clear error message.

From the console log:

[14:58:15] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: island visit Alebrelle
java.lang.NullPointerException: null
	at com.bartz24.voidislandcontrol.PlatformCommand.visit(PlatformCommand.java:182) ~[PlatformCommand.class:?]
	at com.bartz24.voidislandcontrol.PlatformCommand.func_184881_a(PlatformCommand.java:133) ~[PlatformCommand.class:?]
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:88) ~[CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by Bartz24** [comment]
should be fixed in 1.5.1 coming soon
