### ISSUE TITLE
v1.5.2 Spawn-Island does not generate in the specified dimension!

### ISSUE THREAD

**Issue by MSandro** [Bartz24/VoidIslandControl#65]
Hi I am creating a modpack and use this mod to let the player spawn in a structure generated on a AdvancedRocketry Planet. It works fine but the spawn point is on Dim 0 and also the bedrock platform is there. 

Please fix that.

**Comment by Bartz24** [comment]
should be fixed once 1.5.3 is out

**Comment by MSandro** [comment]
is voidislandcontrol-1.5.3.jar realy for MC 1.13.2?

**Comment by Bartz24** [comment]
No. That was a mistake sorry! thought it said 1.12.2...
1.13 is probably going to be skipped as 1.14 is coming somewhat soon I would think

**Comment by MSandro** [comment]
Okay, but it seems that your fix didn't work. If I set the baseDimension to 63 I spawn in the overworld without a island generated and if I type /island create I get a unknown Error.

```
[16:46:01] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command
[16:46:13] [Server thread/WARN]: Couldn't process command: island create
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51]
	at com.bartz24.voidislandcontrol.api.IslandManager.tpPlayerToPos(IslandManager.java:163) ~[IslandManager.class:?]
	at com.bartz24.voidislandcontrol.api.IslandManager.tpPlayerToPosSpawn(IslandManager.java:201) ~[IslandManager.class:?]
	at com.bartz24.voidislandcontrol.EventHandler.spawnPlayer(EventHandler.java:201) ~[EventHandler.class:?]
	at com.bartz24.voidislandcontrol.PlatformCommand.newPlatform(PlatformCommand.java:386) ~[PlatformCommand.class:?]
	at com.bartz24.voidislandcontrol.PlatformCommand.func_184881_a(PlatformCommand.java:107) ~[PlatformCommand.class:?]
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.func_184881_a(CommandOverride.java:88) ~[CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

I have to downgrade to 1.5.2 :(
