### ISSUE TITLE
crash when replacing the bedrock plattform on the spawn with a cube

### ISSUE THREAD

**Issue by MSandro** [Bartz24/VoidIslandControl#67]
Here is the crash log:

```
Time: 1/29/19 9:01 PM
Description: Ticking memory connection

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.bartz24.voidislandcontrol.api.IslandManager.getSpawnOffset(IslandManager.java:194)
	at com.bartz24.voidislandcontrol.EventHandler.playerLogin(EventHandler.java:77)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1937_EventHandler_playerLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
...
```

**Comment by Bartz24** [comment]
The mistake is on your end! I put in something to avoid this crash, but it will not fix your issue!
You didn't put your custom island in the right place or something. make sure to check the mod page for instructions
