### ISSUE TITLE
Anyway to /island create in a non void world?

### ISSUE THREAD

**Issue by Saereth** [Bartz24/VoidIslandControl#84]
I was hoping to use the island control and generation of the mod but not actually use a voidworld. I still have the worldtype set to void but I'm using just enough dimensions to customize dimension 0 with icey worldgen. The /island create command tells me I'm not in a void world type. Is there anyway for me to override this restriction in configs?

**Comment by Saereth** [comment]
as an update I was able to set justenoughdimension to override the generator type to voidworld and the command runs but then it errors
```

[12:12:35] [Server thread/WARN] [minecraft/CommandHandler]: Couldn't process command: base create
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source) ~[?:1.8.0_221]
	at java.util.ArrayList.get(Unknown Source) ~[?:1.8.0_221]
	at com.bartz24.voidislandcontrol.EventHandler.spawnPlat(EventHandler.java:239) ~[EventHandler.class:?]
	at com.bartz24.voidislandcontrol.EventHandler.createSpawn(EventHandler.java:233) ~[EventHandler.class:?]
	at com.bartz24.voidislandcontrol.EventHandler.spawnPlayer(EventHandler.java:197) ~[EventHandler.class:?]
	at com.bartz24.voidislandcontrol.PlatformCommand.newPlatform(PlatformCommand.java:386) ~[PlatformCommand.class:?]
	at com.bartz24.voidislandcontrol.PlatformCommand.execute(PlatformCommand.java:107) ~[PlatformCommand.class:?]
	at com.feed_the_beast.ftbutilities.ranks.CommandOverride.execute(CommandOverride.java:88) ~[CommandOverride.class:?]
	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_221]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_221]
	at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
```

this happens on 1.5.3 and 1.5.2 
any advice on getting this working is highly appreciated

**Comment by Saereth** [comment]
changing off of bedrock island type and to snow (or any other type) resolved this issue, odd
